# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 63bbf8994bde1fa7faee449b9ba43304f2d3dfba80b586c43e20e9f84b994b063558ea9c7112c3beb862b173d7ca9f59a4ab9cf5d3e7d13faa0e81f23ce693b0

test:
  secret_key_base: 1237502356298aa7ec167ef8c22ac2a70f3074222face702456e11655c42a26da4fdc06b10b21fbb581b96278e23ec8bd985a45267018e30ebd9ae3debedf7f5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
